### PR TITLE
resolved the bug and made the youtube video iframe centered

### PR DESCRIPTION
**Pull request by Pariharx7**
```diff
+ <center>
+  <iframe width="560" height="315" src="https://www.youtube.com/embed/3a7avJAbX4g?si=NtwvSYpRyzTel7T7" title="YouTube 
+   video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; 
+    web-share" allowfullscreen></iframe>
+ </center>
```

### CODE REVIEW

**Review by soulee-dev — APPROVED** [review]
Seems good.

**Comment by Pariharx7** [comment]
Can you use the hacktoberfest-accepted label, as it would help me to complete 4 PR during Hacktoberfest challenge.

**Comment by soulee-dev** [comment]
This repo has `hacktoberfest`, so you don't worry about to get accepted from Hacktobefest.

**Comment by Pariharx7** [comment]
Ok

**Pull request merged**
